# Generated by Django 2.2.2 on 2019-09-16 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190904_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
