# Generated by Django 2.2.2 on 2019-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='blog_images'),
        ),
    ]
